In [109]:
print('Hello Wrold')

Hello Wrold


In [110]:
%load_ext autoreload
%autoreload 2

In [111]:
import numpy as np

In [112]:
import sys

In [113]:
sys.version

'3.12.11 (main, Aug 19 2025, 12:38:09) [GCC 9.4.0]'

In [114]:
arr1 = np.array([1, 2, 3, 4])
mask = (arr1 < np.ones(4)* 3)

In [115]:
arr1[mask]

array([1, 2])

In [116]:
arr1[0:2]

array([1, 2])

In [117]:
arr = np.array([1, 2, 3.0])
arr2 = arr 
arr2 *= 2.0
arr

array([2., 4., 6.])

In [118]:
class Parent:
    def __init__(, name):
        .name = name

class Child(Parent):
    @classmethod
    def from_string(cls, name):
        return cls(name)

SyntaxError: invalid syntax (743054732.py, line 2)

In [119]:
p = Parent('Vitia')
type(p)

NameError: name 'Parent' is not defined

In [120]:
pp = Child('Petia')
type(pp)

NameError: name 'Child' is not defined

In [121]:
ppp = Child.from_string('Vania')
type(ppp)

NameError: name 'Child' is not defined

In [122]:
import pandas as pd

In [123]:
class customFrame(pd.DataFrame):
    pass

In [124]:
frame = customFrame()
type(frame)

__main__.customFrame

In [125]:
import tqdm
from psr_lib import interface
import numpy as np
from psr_lib.utils import constants


In [132]:

psr = interface.RadioPulsar.from_file('test_pulsar.toml')
# t=0
# for i in tqdm.tqdm(range(100000)):
#     t += psr.w(0.5, 1, 1.2, 2000)# print(t)



In [57]:
class PerformanceTestClass:
    def __init__(self, a, b, c, d):
        self.a = a
        self.b = b
        self.c = c
        self.d = d
    
    def do_stuff1(self):
        self.a = np.sin(self.a**2 + self.a * self.b - self.c**0.5 * constants.Bcr12)**2.1 

    def do_stuff2(self):
        self.b = np.cos(self.b**2 + self.d * self.b - self.a**0.5 * constants.Bcr12)**3.1 

    def do_stuff3(self):
        self.c = np.sin(self.a * self.d - self.b * self.c) - np.sin(self.d * self.c - self.c * self.b * constants.Bcr12)

    def do_stuff4(self):
        self.d = np.cos(self.a * self.c - self.b * self.b) - np.sin(self.d * self.c - self.a * self.b * constants.Bcr12)

    def do_stuff(self):
        # self.value = (np.abs(self.value**2 + self.value - np.sin(self.value)**3))**0.5 - (np.abs(self.value**2 + self.value - np.sin(self.value)**3))**0.1
        # self.do_stuff1()
        # self.do_stuff2()
        # self.do_stuff3()
        self.do_stuff4()


    def do_some_serious_staff(self, N_it=1000000):
        for i in tqdm.tqdm(range(N_it)):
            self.do_stuff()
    

In [59]:
perf_test = PerformanceTestClass(1.5, 10, 12, 2.2)

In [77]:
perf_test.do_some_serious_staff()

  0%|          | 0/1000000 [00:00<?, ?it/s]

100%|██████████| 1000000/1000000 [00:03<00:00, 311872.66it/s]


In [84]:
a, b, c, d = 1.5e8, 1000, 12e-5, 2.2

def do_stuff_faster(d):
    return np.cos(a * c - b *  b)**2 + np.sin(a * c - b *  b)**2 - np.sin(d * c - a * b * 44.15225118483413)

for i in tqdm.tqdm(range(1000000)):
    # a = np.sin(a**2 +   a * b - c**0.5 * 44.15225118483413)**2.1
    # b = np.cos(b**2 + d * b - a**0.5 * 44.15225118483413)**3.1
    # c = np.sin(a * d - b * c) - np.sin(d * c - c * b * 44.15225118483413)
    d = np.cos(a * c - b *  b)**2 + np.sin(a * c - b *  b)**2 - np.sin(d * c - a * b * 44.15225118483413)
    # d = do_stuff_faster(d)

100%|██████████| 1000000/1000000 [00:04<00:00, 204456.14it/s]


In [88]:
print(psr.KRc)

0.8250000000000001


In [64]:
constants.e_lambda_bar

3.864468864468864e-11

In [ ]:
psr.KRc

0.8250000000000001

In [73]:
def w1(x_em, r_em, r, Eph):
    """
    pair production probability
    Eph should be normalized to m_e c^2
    return: probability density (in w dl, dl expressed in R star)
    """
    if (r - r_em) / r_em < 1e-15:
        return 0
    psi_inf = r_em / (4/3 * 1200000.0 / 21667 / (x_em) * np.sqrt(r_em))
    # psi = self.psi_inf(x_em, r_em) * (1 - r_em/r)
    psi = psi_inf * (1 - r_em/r)
    return 0.23 * 1 / 137 / (3.86e-11/1200000) * 1/r**3 / (44.152) * psi * np.exp(-8/3 / Eph * 44.152/ (1/r**3) / psi)

In [74]:

t=0
for i in tqdm.tqdm(range(100000)):
    t += w1(0.5, 1, 1.2, 2000)
print(t)


100%|██████████| 100000/100000 [00:00<00:00, 205231.01it/s]

5.478986860466124e-26
