In [ ]:
print('Hello Wrold')

Hello Wrold


In [46]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
import numpy as np

In [5]:
import sys

In [6]:
sys.version

'3.12.11 (main, Aug 19 2025, 12:38:09) [GCC 9.4.0]'

In [50]:
arr1 = np.array([1, 2, 3, 4])
mask = (arr1 < np.ones(4)* 3)

In [51]:
arr1[mask]

array([1, 2])

In [52]:
arr1[0:2]

array([1, 2])

In [11]:
arr = np.array([1, 2, 3.0])
arr2 = arr 
arr2 *= 2.0
arr

array([2., 4., 6.])

In [7]:
class Parent:
    def __init__(self, name):
        self.name = name

class Child(Parent):
    @classmethod
    def from_string(cls, name):
        return cls(name)

In [3]:
p = Parent('Vitia')
type(p)

__main__.Parent

In [6]:
pp = Child('Petia')
type(pp)

__main__.Child

In [9]:
ppp = Child.from_string('Vania')
type(ppp)

__main__.Child

In [10]:
import pandas as pd

In [11]:
class customFrame(pd.DataFrame):
    pass

In [12]:
frame = customFrame()
type(frame)

__main__.customFrame